name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pt6000/hello-world-docker-action:latest
      
    - name: docker push
      run: |
        docker push pt6000/hello-world-docker-action
        
    - name: Tag the image
      run: |
        docker tag pt6000/hello-world-docker-action:latest pt6000/dct-demo-12:1
        docker push pt6000/dct-demo-12:1
        
    - name: Testing phase
      run: |        
        sudo mount -t cifs //githubreporelstorage.file.core.windows.net/sharefile . -o vers=3.0,username=githubreporelstorage,password=${{ secrets.AZURE_PASS }},dir_mode=0777,file_mode=0777
        cp action.yml action_new.yml
        ls

    - name: Create Code Signing Certificate and Cert Key
      run: |
          echo "${{secrets.CERTIFICATE_KEY}}" > cert_key_6.key
          chmod 600 cert_key_6.key
          echo "${{secrets.CERTIFICATE}}" > cert_6.crt
          chmod 600 cert_6.crt         
      #    apt-get update       
      #    apt-get install libnss3-tools
      #   certutil -decode cert_key.txt cert_key.key
      #   mkdir certificate
          
    - name: Load the Cert key
      run: |
       docker trust key load cert_key_6.key --name dock_cert_key_6 <<-EOF
         ${{ secrets.CERTIFICATE_PASS }}
         ${{ secrets.CERTIFICATE_PASS }}
       EOF
       
    - name: Add signer
      run: |
        { echo '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}';
          echo '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}';
          sleep 15 && echo '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}';
          echo '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}';
        } | docker trust signer add --key cert_6.crt dock_cert_key_6 pt6000/dct-demo-12:1         
#       docker trust signer add --key cert.crt dock_cert_key pt6000/dct-demo-6:1 <<-'EOF'
#        ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#        ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#        ${{ secrets.CERTIFICATE_PASS }}
#        EOF
              
#    Set-Content -Path certificate\certificate.txt -Value '${{secrets.CERTIFICATE}}'
      #    certutil -decode certificate\certificate.txt certificate\certificate.pfx

      #  docker trust signer add --key /keys/server.crt cert_key pt6000/dct-demo-5:1-<<EOF  
        #docker trust signer add --key /keys/server.crt my_key pt6000/dct-demo-5:1-<<EOF
     #docker trust signer add --key /home/runner/work/hello-world-docker-action/hello-world-docker-action/test_key_6.pub test_key_6 pt6000/dct-demo-6:1 <<EOF
 #   - name: Generate key
 #     run: |
 #       docker trust key generate test_key_7 <<EOF
 #        ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 #        ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
 #        EOF
         
         
#    - name: Add signer
#      run: |
#        docker trust signer add --key test_key_7.pub test_key_7 pt6000/dct-demo-6:1 <<EOF
#          ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#          ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#          ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#          EOF
       
    - name: Tag the signed image
      run: |
       docker tag pt6000/dct-demo-12:1 pt6000/dct-demo-12:1-signed
        
    - name: Sign the image
      run: |
        docker trust sign pt6000/dct-demo-12:1-signed <<EOF
         ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
         EOF     
        
    - name: Push the signed image
      run: |    
        docker push pt6000/dct-demo-12:1-signed

    - name: DCT On
      run: |      
        export DOCKER_CONTENT_TRUST=1  
      
    - name: Pull the unsigned image (this will fail) 
      run: |    
        docker pull pt6000/dct-demo-12:1    

    - name: DCT Off
      run: |      
        export DOCKER_CONTENT_TRUST=0 
      
    - name: Pull the unsigned image (this will pass)
      run: |    
        docker pull pt6000/dct-demo-12:1    
  
      
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: pt6000/dct-demo-12:1-signed
        
        
    - name: Download image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: pt6000/dct-demo-12:1-signed

        
    - name: Tar the image
      run: |      
        docker save pt6000/dct-demo-12:1 | gzip > test_latest.tar.gz
        ls

        
        
