name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag pt6000/hello-world-docker-action:latest
      
    - name: docker push
      run: |
        docker push pt6000/hello-world-docker-action
        
    - name: Tag the image
      run: |
        docker tag pt6000/hello-world-docker-action:latest pt6000/dct-demo-5:1
        docker push pt6000/dct-demo-5:1
                
    - name: DCT On
      run: |      
        export DOCKER_CONTENT_TRUST=1  
        
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: pt6000/dct-demo-5:1
        
        
        
